version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '[%(asctime)s - %(name)s] %(module)s:%(funcName)s - %(message)s'
    datefmt: '%a, %Y-%m-%d, %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: default

loggers:
  chatbot:
    level: DEBUG
    handlers:
      - console
    propagate: false

  root:
    level: INFO
    handlers:
      - console